[crates]
aes-gcm = "0.10.3"
arc-swap = "1.8.2"
anyhow = "1.0.102"
async-trait = "0.1.89"
base64 = "0.22.1"
bevy = "0.18.1"
cc = "1.2.56"
cosmic-text = "0.18.2"
env_logger = "0.11.9"
dirs = "6.0.0"
futures-util = "0.3.32"
getrandom = "0.4.2"
image = "0.25.10"
iced = "0.14.0"
flate2 = "1.1.9"
log = "0.4.29"
libc = "0.2.183"
leptos = "0.8.17"
nu-plugin = "0.111.0"
nu-plugin-test-support = "0.111.0"
nu-protocol = "0.111.0"
nu-test-support = "0.111.0"
regex = "1.12.3"
regex-cursor = "0.1.5"
reqwest = "0.13.2"
resvg = "0.47.0"
ropey = "1.6.1"
roxmltree = "0.21.1"
serde = "1.0.228"
serde_json = "1.0.149"
sha2 = "0.10.9"
similar = "2.7.0"
slab = "0.4.12"
tar = "0.4.44"
thiserror = "2.0.18"
tokio = "1.50.0"
tokio-tungstenite = "0.28.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
tungstenite = "0.28.0"
tree-sitter = "0.2.3"
tree-sitter-rust = "0.24.0"
tree-house-bindings = "0.2.3"
url = "2.5.8"
ureq = "3.2.0"
uuid = "1.22.0"
windows-sys = "0.61.2"
zip = "8.2.0"
