{
  pkgs,
  config,
  lib,
  inputs ? { },
  ...
}:

let
  cfg = config.rustEnv.managedCargo;
  managedCargoEnabled = cfg.enable;
  managedCargoMergeScript = ./merge-managed-cargo.py;
  managedCargoTomlFormat = pkgs.formats.toml { };
  editablePaths = import ./editable-paths.nix {
    inherit config inputs lib;
  };
  resolveFromRoot = path: if lib.hasPrefix "/" path then path else "${config.devenv.root}/${path}";
  pathIsInsideRoot =
    path:
    let
      root = toString config.devenv.root;
      rootPrefix = "${root}/";
    in
    path == root || lib.hasPrefix rootPrefix path;
  managedCargoCatalogPath = resolveFromRoot cfg.catalogPath;
  managedCargoSpecPath = resolveFromRoot cfg.specPath;
  managedCargoCatalogEditPath = editablePaths.editablePathFor managedCargoCatalogPath;
  managedCargoSpecEditPath = editablePaths.editablePathFor managedCargoSpecPath;
  managedCargoHeader = ''
    # GENERATED BY DEVENV: DO NOT EDIT DIRECTLY
    #
    # Project-local manifest and dependency settings (no version numbers): `${managedCargoSpecEditPath}`
    # To add globally managed crates (with version numbers):
    # - check latest crate releases using `cargo info`
    # - add to polyrepo-global source of true, edit: `${managedCargoCatalogEditPath}`
    # - refresh nix store symlinks in local project: `devenv shell --nu-tui --no-eval-cache --refresh-eval-cache bash -lc "cat Cargo.toml"`
    #
  '';
  managedCargoSourcePath = resolveFromRoot (
    if cfg.sourcePath != null then cfg.sourcePath else dirOf cfg.specPath
  );
  managedCargoShouldMaterialize =
    managedCargoEnabled && cfg.outputPath != null && pathIsInsideRoot managedCargoSpecPath;
  managedCargoManifestJsonText =
    if managedCargoEnabled then
      builtins.readFile (
        pkgs.runCommand "cargo-manifest.json"
          {
            nativeBuildInputs = [ pkgs.python3 ];
            passAsFile = [
              "catalogToml"
              "specToml"
            ];
            catalogToml = builtins.readFile managedCargoCatalogPath;
            specToml = builtins.readFile managedCargoSpecPath;
          }
          ''
            python3 ${managedCargoMergeScript} "$catalogTomlPath" "$specTomlPath" > "$out"
          ''
      )
    else
      "";
  managedCargoManifestValue =
    if managedCargoManifestJsonText != "" then builtins.fromJSON managedCargoManifestJsonText else null;
  managedCargoManifestFile =
    if managedCargoManifestValue != null then
      pkgs.writeText "Cargo.toml" (
        managedCargoHeader
        + builtins.readFile (managedCargoTomlFormat.generate "Cargo.toml.body" managedCargoManifestValue)
      )
    else
      null;
  managedCargoCatalogFile =
    if managedCargoEnabled then
      pkgs.writeText "rust-deps-catalog.toml" (builtins.readFile managedCargoCatalogPath)
    else
      null;
  managedCargoSourceTree =
    if managedCargoEnabled then
      pkgs.runCommand "${baseNameOf managedCargoSourcePath}-cargo-source" { } ''
        mkdir -p "$out"
        cp -R ${
          builtins.path {
            path = managedCargoSourcePath;
            name = "${baseNameOf managedCargoSourcePath}-source";
          }
        }/. "$out"/
        chmod -R u+w "$out"
        rm -f "$out/Cargo.toml"
        cp ${managedCargoManifestFile} "$out/Cargo.toml"
      ''
    else
      null;
in
{
  options.rustEnv.managedCargo = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Generate Cargo.toml from a repo-owned Cargo.poly.toml and a shared crate version catalog.";
    };

    catalogPath = lib.mkOption {
      type = lib.types.str;
      default = toString ./Cargo.catalog.toml;
      description = "Path to the shared crate version catalog TOML.";
    };

    specPath = lib.mkOption {
      type = lib.types.str;
      default = "Cargo.poly.toml";
      description = "Repo-owned Cargo manifest spec TOML without crates.io versions.";
    };

    outputPath = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "Cargo.toml";
      description = "Output path for the generated Cargo manifest. Set to null to disable workspace materialization and expose only outputs.cargo_manifest.";
    };

    sourcePath = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Repo source root used for outputs.cargo_source_tree. Defaults to the directory containing specPath.";
    };
  };

  config = lib.mkMerge [
    {
      assertions = lib.optionals managedCargoEnabled [
        {
          assertion = builtins.pathExists managedCargoSpecPath;
          message = "rustEnv.managedCargo.enable is true but specPath does not exist: ${managedCargoSpecPath}";
        }
        {
          assertion = builtins.pathExists managedCargoSourcePath;
          message = "rustEnv.managedCargo.enable is true but sourcePath does not exist: ${managedCargoSourcePath}";
        }
      ];

      outputs = lib.mkIf managedCargoEnabled {
        cargo_manifest = managedCargoManifestFile;
        cargo_source_tree = managedCargoSourceTree;
        rust_deps_catalog = managedCargoCatalogFile;
      };
    }
    (lib.mkIf managedCargoShouldMaterialize {
      files."${cfg.outputPath}".source = managedCargoManifestFile;
    })
  ];
}
